[package]
name = "mergeip"
version = "0.1.0"
authors = ["Filip Horňák <sleepy771@github.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
lazy_static = "1.0"
argparse = "0.2.1"
