[package]
name = "ipaggregator-rs"
version = "0.1.0"
authors = ["Filip Horňák <sleepy771@github.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
lazy_static = "1.0"
argparse = "0.2.1"
kafka = "0.7.0"
nom = "3.2.1"
log = "0.4"
log4rs = "0.8.0"
