auto_use_zeroed: true/home/filip/develop/rust/Subnetizers
auto_use_broadcast: true
publish_timer: 30
receiver:
  receiver: udp
  udp_address: 127.0.0.1:8080
sender:
  sender: udp
  udp_address: 127.0.0.1:8081

