auto_use_zeroed: true
auto_use_broadcast: true
publish_timer: 30
receiver:
  receiver: udp
  udp_address: 127.0.0.1:8080
#  kafka:
#    hosts: [ localhost:9092 ]
#    topic: ips-in
#    group: ips
sender:
  sender: udp
  udp_address: 127.0.0.1:8081
#  kafka:
#    hosts: [ localhost:9092 ]
#    topic: ips-out
#    ack_duration: 1

